
nouns = {
    "alphabet": ["Alphabet", "das"],
    "monkey": ["Affe", "der"],
    "ant": ["Ameise", "die"],
    "banana": ["Banane", "die"],
    "boat": ["Boot", "das"],
    "bus": ["Bus", "der"],
    "CD": ["CD", "die"],
    "camp": ["Camp", "das"],
    "roof": ["Dach", "das"],
    "lady": ["Dame", "die"],
    "elephant": ["Elephant", "der"],
    "donkey": ["Esel", "der"],
    "strawberry": ["Erdbeere", "die"],
    "window": ["Fenster", "das"],
    "factory": ["Fabrik", "die"],
    "violin": ["Geige", "die"],
    "guitar": ["Gitarre", "die"],
    "heart": ["Herz", "das"],
    "dog": ["Hund", "der"],
    "house": ["Haus", "das"],
    "hedgehog": ["Igel", "der"],
    "island": ["Insel", "die"],
    "boy": ["Junge", "der"],
    "jacket": ["Jacke", "die"],
    "yacht": ["Yacht", "die"],
    "cook": ["Koch", "der"],
    "cheese": ["Käse", "der"], # ä
    "king": ["König", "der"], # ö
    "teacher": ["Lehrer", "der"],
    "lion": ["Löwe", "der"], # ö
    "lamp": ["Lampe", "die"],
    "lamb": ["Lamm", "das"],
    "moon": ["Mond", "der"],
    "coat": ["Mantel", "der"],
    "mouse": ["Maus", "die"],
    "night": ["Nacht", "die"],
    "fog": ["Nebel", "der"],
    "fruit": ["Obst", "das"],
    "nose": ["Nase", "die"],
    "grandpa": ["Opa", "der"],
    "orange": ["Orange", "die"],
    "horse": ["Pferd", "das"],
    "pepper": ["Paprika", "der"],
    "square": ["Quadrat", "das"],
    "slide": ["Rustche", "die"],
    "radio": ["Radio", "das"],
    "rain": ["Regen", "der"],
    "sun": ["Sonne", "die"],
    "bag": ["Sack", "der"],
    "juice": ["Saft", "der"],
    "tomato": ["Tomate", "die"],
    "table": ["Tisch", "der"],
    "door": ["Tür", "die"], # ü
    "clock": ["Uhr", "die"],
    "subway": ["U-Bahn", "die"],
    "bird": ["Vogel", "der"],
    "vase": ["Vase", "die"],
    "wine": [ "Wein", "der"],
    "water": ["Wasser", "das"],
    "forest": ["Wald", "der"],
    "father": ["Vater", "der"],
    "yoga": [ "Yoga", "das"],
    "yard": ["Yard", "das"],
    "zebra": ["Zebra", "das"],
    "tooth": ["Zahn", "der"],
    "zoo": ["Zoo", "der"],
    "anger": ["Ärger", "der"], # Ä
    "oil": ["Öl", "das"], # Ö
    "exercise": ["Übung", "die"], # Ü
    "foot": ["Fuß", "der"], # ß
    "egg": ["Ei", "das"],
    "ladder": ["Leiter", "die"],
    "bucket": ["Eimer", "der"],
    "owl": ["Eule", "die"],
    "pig": ["Schwein", "die"],
    "street": ["Straße", "die"], # ß
    "sport": ["Sport", "der"],
    "game": ["Spiel", "das"],
    "books": ["Bücher", "die"], # ü
    "blanket": ["Decke", "die"],
    "piece": ["Stück", "das"], # ü
    "place": ["Platz", "der"],
    "knee": ["Knie", "das"],
    "kitchen": ["Küche", "die"],
    "child": ["Kind", "das"],
    "man": ["Mann","der"],
    "woman": ["Frau","die"],
    "cupboard": ["Schrank", "der"],
    "cat": ["Katze", "die"],
    "cup/mug": ["Tasse", "die"],
    "glass": ["glas", "das"],
    "plate": ["Teller", "der"],
    "shelf": ["Regal", "das"],
    "tree": ["Baum", "der"],
    "pen/pencil": ["Stift", "der"],
    "bicycle": ["Fahrrad", "das"],
}
verbs = {
    "come": ["kommen", "akk"],
    "eat": ["essen", "akk"],
    "steal": ["stehlen", "akk"],
    "see": ["sehen", "sehen"],
    "go/walk": ["gehen", "akk"],
    "know": ["wissen", "akk"],
    "do/make": ["machen", "akk"],
    "say": ["sagen", "akk"],
    "read": ["lesen", "akk"],
    "play": ["spielen", "akk"],
    "need/require": ["brauchen", "akk"],
    "buy": ["kaufen", "akk"],
    "to shop": ["einkaufen", "akk"],
    "find": ["finden", "akk"],
    "search": ["suchen", "akk"],
    "help": ["helfen", "dat"],
    "want/would like": ["möchten", "akk"],
    "to taste": ["schmecken", "dat"],
    "to get/obtain": ["bekommen", "akk"],
    "talk": ["reden", "akk"],
    "tell off": ["quatschen", "akk"],
    "to chat": ["unterhalten", "akk"],
    "to start": ["anfangen", "akk"],
    "to arrive": ["ankommen", "akk"],
    "to call/phone": ["anrufen", "akk"],
    "get up": ["aufstehen", "akk"],
    "begin": ["beginnen", "akk"],
    "stay": ["bleiben", "akk"],
    "bring/take": ["bringen", "akk"],
    "think": ["denken", "dat"],
    "allowed to": ["dürfen", "akk"],
    "drive": ["fahren", "akk"],
    "to catch": ["fangen", "akk"],
    "watch TV": ["fernsehen", "akk"],
    "fly": ["fliegen", "akk"],
    "give": ["geben", "akk"],
    "can/be able": ["können", "akk"],
    "like/want": ["mögen", "akk"],
    "must": ["müssen", "akk"],
    "to take": ["nehmen", "akk"],
    "call": ["rufen", "akk"],
    "swim": ["schwimmen", "akk"],
    "sing": ["singen", "akk"],
    "should": ["sollen", "akk"],
    "stand": ["stehen", "akk"],
    "meet": ["treffen", "akk"],
    "drink": ["trinken", "akk"],
    "understand": ["verstehen", "akk"],
    "hurt": ["wehtun", "dat"],
    "want": ["wollen", "akk"],
    "do": ["tun", "akk"],
    "cook": ["kochen", "akk"],
    "clean up": ["aufräumen", "akk"],
    "to hoover": ["staubsaugen", "akk"],
    "to have beakfast": ["frühstücken", "akk"],
    "to work": ["arbeiten", "akk"],
    "to miss": ["fehlen", "dat"],
    "to like": ["gefallen", "dat"],
    "to belong": ["gehören", "dat"],
    "to believe": ["glauben", "dat"],
    "to listen": ["zuhören", "dat"],
    "to follow": ["folgen", "dat"],
    "to trust": ["vertrauen", "dat"],
    "to disagree": ["widersprechen", "dat"],
    "to accept": ["zusagen", "dat"],
}
introducing = {
    "What is your name?[with Name]": ["Wie is dein Name"],
    "My name is[with Name]": ["Mein Name ist"],
    "Who are you?": ["Wer bist du"],
    "I am": ["Ich bin"],
    "What is your name?": ["Wie heißt du"],
    "My name is": ["Ich heiße"],
    "How old are you?": ["Wie alt bist du"],
    "I am 17 years old": ["Ich bin 17 Jahre alt"],
    "Which languages do you speak?": ["Welche Sprachen sprichst du"],
    "I speak English and a little German": ["Ich spreche Englisch und ein wenig Deutsch"],
    "How are you?": ["Wie geht es dir"],
    "I am fine": ["Es geht mir gut"],
    "Where are you from?": ["Woher kommst du"],
    "I come from Bulgaria": ["Ich komme aus Bulgarien"]
}
greeting = {
    "Hello": ["Hallo"],
    "Good morning": ["Guten Morgen"],
    "Good day": ["Guten Tag"],
    "Good afternoon/evening": ["Guten Abend"],
    "Good night": ["Gute Nacht"],
    "Welcome": ["Herzlich Willkommen"],
    "It's nice to meet you": ["Es freut mich Sie kennenzulernen"],
    "Goodbye[in person]": ["Auf Wiedersehen"],
    "Goodbye[on the phone]": ["Auf Wiederhören"],
    "Bye": ["Tschüs"],
    "See you soon": ["Bis Bald"]
}
countries = {
    "Germany":["Deutschland"],
    "Austria":["Östereich"],
    "Portugal":["Portugal"],
    "France":["Frankreich"],
    "Great Britan":["Großbritannien"],
    "Japan":["Japan"],
    "South Africa":["Südafrika"],
    "Canada":["Kanada"],
    "China":["China"],
    "Switzerland":["die Schweitz"],
    "Turkey":["die Türkei"],
    "USA":["die USA"],
    "English":["Englisch"],
    "French":["Französisch"],
    "Spanish":["Spanisch"],
    "Italian":["Italienisch"],
    "Chinese":["Chinesisch"],
    "Russian":["Russisch"],
    "German":["Deutsch"]
}
family = {
    "family": ["Familie", "die"],
    "mother": ["Mutter", "die"],
    "father": ["Vater", "der"],
    "daughter": ["Tochter", "die"],
    "son": ["Sohn", "der"],
    "grandmother": ["Großmutter", "die"],
    "grandfather": ["Großvater", "der"],
    "aunt": ["Tante", "die"],
    "uncle": ["Onkel", "der"],
    "sister": ["Schwester", "die"],
    "brother": ["Bruder", "der"],
    "cousin": ["Cousin", "der"],
    "granddaughter": ["Enkelin", "die"],
    "grandson": ["Enkel", "der"],
    "niece": ["Nichte", "die"],
    "nephew": ["Neffe", "der"],
    "wife": ["Ehefrau", "die"],
    "husband": ["Ehemann", "der"],
    "daughter-in-law": ["Schwiegertochter", "die"],
    "son-in-law": ["Schwiegersohn", "der"],
    "mother-in-law": ["Schwiegermutter", "die"],
    "father-in-law": ["Schwiegervater", "der"],
    "brother-in-law": ["Schwager", "der"],
    "sister-in-law": ["Schwägerin", "die"],
    "baby": ["Baby","das"],
    "child": ["Kind","das"],
    "boy": ["Junge","der"],
    "girl": ["Mädchen", "das"], 
    "teenager": ["Jugendliche", "die"],
    "adult": [ "Erwachsene","der"]     
}
foods = {
    "beer": ["Bier", "das", "Biere"],
    "bun": ["Brotchen", "das", "Brötchen"],
    "bread": ["Brot", "das", "Brote"],
    "egg": ["Ei", "das", "Eier"],
    "butter": ["Butter", "die"],
    "tomato": ["Tomate", "die", "Tomaten"],
    "potatoe": ["Kartoffel", "die", "Kartoffeln"],
    "carrot": ["Karotte", "die", "Karotten"],
    "fruit": ["Obst", "das"],
    "vegetable": ["Gemüse", "das"],
    "lettuce/salad": ["Salat", "der"],
    "onion": ["Zwiebel", "die"],
    "garlic": ["Knoblauch", "der"],
    "apple": ["Apfel", "der", "Äpfel"],
    "banana": ["Banane", "die", "Bananen"],
    "orange": ["Orange", "die", "Orangen"],
    "grapes": ["Trauben", "die"],
    "pear": ["Birne", "die", "Birnen"],
    "coffe": ["Kaffee", "der"],
    "tea": ["Tee", "der"],
    "wine": ["Wein", "der"],
    "water": ["Wasser", "das"],
    "yogurt": ["Joghurt", "der"],
    "cheese": ["Käse", "der"],
    "cream": ["Sahne", "die"],
    "milk": ["Milch", "die"],
    "meat/flesh": ["Fleisch", "das"],
    "sausage": ["Wurst", "die"],
    "pork": ["Schweinefleisch", "das"],
    "beef": ["Rindfleisch", "das"],
    "chicken": ["Hänchenfleisch", "das"],
    "lamb": ["Lammfleisch", "das"],
    "fish": ["Fisch", "der"],
    "salt": ["Salz", "das"],
    "pepper": ["Pfeffer", "das"],
    "sugar": ["Zucker", "der"],
    "cake": ["Kuchen", "der"],
    "pasta/noodles": ["Nudeln", "die"],
    "rice": ["Reis", "der"],
    "flour": ["Mehl", "das"],
    "supermarket": ["Supermarkt", "der"],
    "shop": ["Laden", "der"],
    "bakery": ["Bäckerei", "die"],
    "market": ["Markt", "der"],
    "butcher's shop": ["Merzgerei", "der"],
    "flower shop": ["Blumenladen", "der"],
    "man seller": ["Verkäufer", "der"],
    "woman seller": ["Verkäuferin", "die"],
    "kilo": ["Kilogramm"],
    "liter": ["Liter", "der"],
    "bottle": ["Flasche", "die","Flaschen"],
    "pack/package": ["Packung", "die", "Packungen"],
    "cup": ["Becher", "der"],
    "can": ["Dose", "die", "Dosen"],
    "How much does is cost?": ["Wie viel kostet"],
    "Anything else?": ["Sonst noch etwas"],
    "This makes (smetka)": ["Das macht dann"],
    "tastes good": ["schmeckt gut"],
    "menu": ["Speisekarte","die"],
    "starter": ["Vorspeise","die"],
    "soup": ["Suppe","die"],
    "main course": ["Haupgericht","das"],
    "dessert": ["Nachtisch","der"],
    "jam": ["Konfitüre","die"],
    "ham": ["Schinken","der"],
    "juice": ["Saft","der"],
    "drinks": ["Getränke","die"],
    "breakfast": ["Frühstück","das"],
    "lunch": ["Mittagessen","das"],
    "dinner": ["Abendessen","das"],
    "slice": ["Scheibe","die"],
    "straw": ["Strohhalm","der"],
    "scrambled eggs": ["Rührei","das"],
    "pancakes": ["Pfannkuchen","der"],
    "gin": ["Gin","der"],
    "vodka": ["Wodka","der"],
    "whiskey": ["Whisky","der"],
    "rum": ["Rum","der"],
    "liqueur": ["Likör","der"],
    "mayonnaise": ["Majonäse","die"],
    "vinegar": ["Essig","der"],
    "sauce": ["Soße","die"],
    "mashed": ["püriert"],
    "baked": ["gebacken"],
    "fried": ["gebraten"],
    "peanut": ["Erdnuss","die"],
    "cashew": ["Cashewnuss","die"],
    "hazelnut": ["Haselnuss","die"],
    "almond": ["Mandel","die"],
    "peach": ["Pfirsich","der"],
    "pineapple": ["Ananas","die"],
    "aprikot": ["Aprikose","die"],
    "tangarine/clementine": ["Mandarine","die"],
    "lemon": ["Zitrone","die"],
    "aubergine/eggplant": ["Aubergine","die"],
    "mushroom": ["Pilz","der"],
    "pumpkin": ["Kürbis","der"],
    "cucumber": ["Gurke","die"],
    "coconut": ["Kokosnuss","die"],
}
personalInfo = {
    "flat/apartment": ["Wonung", "die"],
    "age": ["Alter", "das"],
    "birthplace": ["Geburtsort", "der"],
    "home country": ["Heimatland", "das"],
    "city/town (where you live)": ["Wohnort", "der"],
    "post/zip number": ["Postleintzahl", "die"],
    "divorced": ["geschieden"],
    "married": ["verheiratet"],
    "widowed": ["verwitwet"],
    "capital": ["Hauptstadt"]
}
Wquest = {
    "Where": ["Wo"],
    "Who": ["Wer"],
    "Where for a direction": ["Wohin"],
    "What": ["Was"],
    "How": ["Wie"],
    "When": ["Wann"],
    "How much": ["Wieviel"],
    "Which": ["Welche"],
    "From where": ["Woher"],
    "really": ["Wirklich"],
} 
importantWords = {
    "something/anything": ["etwas"],
    "more": ["mehr"],
    "for": ["für"],
    "or": ["oder"],
    "also": ["auch"],
    "so/therefore": ["also"],
    "still/yet/even": ["noch"],
    "by/of/from": ["von"],
    "in": ["in"],
    "at the/in the": ["im"],
    "here": ["hier"],
    "late": ["spät"],
    "later/after": ["später"],
    "enough": ["genung"],
    "money": ["Geld", "das"],
    "today": ["heute"],
    "nowadays": ["heutzutage"],
    "about/by": ["über"],
    "with": ["mit"],
    "nonsense": ["quatsch"],
    "once again": ["noch ein Mal"],
    "example": ["Beispiel"],
    "for example": ["zum Beispiel"],
    "almost": ["fast"],
    "North": ["Norden", "der"],
    "East": ["Osten", "der"],
    "South": ["Süden", "der"],
    "West": ["Westen", "der"],
    "slolwy": ["langsam"],
    "no idea": ["keine Ahnung"],
    "sweet": ["süß"],
    "fresh": ["frisch"],
    "exactly": ["genau"],
    "different": ["anders"],
    "never": ["nie"],
    "happy": ["glücklich"],
    #"": [""],
    #"": [""],
    #"": [""],
    #"": [""],
    #"": [""],
    #"": [""],
    #"": [""],
}
apartment = {
    "day": ["Tag", "der"],
    "morning": ["Morgen", "der"],
    "10-12PM": ["Vormittag", "der"],
    "noon": ["Mittag", "der"],
    "afternoon": ["Nachmittag", "der"],
    "evening": ["Abend", "der"],
    "night": ["Nacht", "die"],
    "midnight": ["Mitternacht", "die"],
    "lunch": ["Mittagessen", "das"],
    "dinner": ["Abendessen", "das"],
    "apartment": ["Wohnung", "die", "Wohnungen"],
    "house": ["Haus", "das", "Häuser"],
    "room": ["Zimmer", "das", "Zimmer"],
    "living room": ["Wohnzimmer", "das"],
    "bedroom": ["Schlafzimmer", "das"],
    "children room": ["Kinderzimmer", "das"],
    "dining room": ["Esszimmer", "das"],
    "working room": ["Arbeitszimmer", "das"],
    "guest room": ["Gästezimmer", "das"],
    "toilet": ["Toilette", "die"],
    "bathroom": ["Bad", "das"],
    "bathtub": ["Badewanne", "die"],
    "corridor": ["Flur", "der"],
    "balcony": ["Balkon", "der"],
    "garage": ["Garage", "die"],
    "terrace": ["Terasse", "die"],
    "kitchen": ["Küche", "die"],
    "cellar": ["Keller", "der"],
    "elevator": ["Fahrstuhl", "der"],
    "floor": ["Stock", "der"],
    "rent": ["Miete", "die"],
    "utilities": ["Nebenkosten", "die"],
    "electricity": ["Storm", "der"],
    "warm water": ["Warmwasser", "das"],
    "cold water": ["Kaltwasser", "das"],
    "heating": ["Heizung", "die"],
    "deposit": ["Kaution", "die"],
    "furnished": ["mobiert"],
    "parking spot": ["Parkplatz", "der"],
    "furniture": ["Möbel", "die"],
    "shower cabin": ["Duschkabine", "die"],
    "sink": ["Waschbecken", "das"],
    "washing machine": ["Waschmaschine", "die"],
    "mirror": ["Spiegel", "der"],
    "wardrobe": ["Schrank", "der", "Schränke"],
    "appliences": ["Elektrogerät", "das"],
    "stove/oven": ["Herd", "der"],
    "fridge": ["Kühlschrank", "der"],
    "dishwasher": ["Geschirrspülmaschine", "die"],
    "dining table": ["Esstisch", "der"],
    "shelf": ["Regal", "das"],
    "sofa": ["Sofa", "das"],
    "armchair": ["Sessel", "der", "Sessel"],
    "lamp": ["Lamp", "die", "Lampen"],
    "chair": ["Stuhl", "der", "Stühle"],
    "TV": ["Fernseher", "der"],
    "bed": ["Bett", "das"],
    "hoover": ["Staubsauger", "der"],
    "curtains": ["Gardinen", "die"],
    "window": ["Fenster", "das", "Fenster"],
    "door": ["Tür", "die", "Türen"],
    "carpet": ["Teppich", "der"],
}
adjectives = {
    "red": ["rot"],
    "yellow": ["gelb"],
    "blue": ["blau"],
    "green": ["grün"],
    "orange": ["orange"],
    "white": ["weiß"],
    "black": ["schwarz"],
    "brown": ["braun"],
    "gray": ["grau"],
    "pink": ["pink"],
    "purple": ["violett"],
    "light": ["hell"],
    "dark": ["dunkel"],
    "warm": ["warm"],
    "cold": ["kalt"],
    "beautiful": ["schön"],
    "bad": ["schlecht"],
    "good": ["gut"],
}
weather = {
    "weather": ["Wetter", "das"],
    "thermometer": ["Thermometer", "das"],
    "degrees": ["Grad", "das"],
    "sun": ["Sonne", "die"],
    "sunshine": ["Sonneschein", "der"],
    "sunny": ["sonnig"],
    "wind": ["Wind", "der"],
    "windy": ["windig"],
    "rain": ["Regen", "der"],
    "rainy": ["regnerisch"],
    "to rain": ["regnen"],
    "snow": ["Schnee", "der"],
    "to snow": ["schneien"],
    "Spring": ["Frühling", "der"],
    "Summer": ["Sommer", "der"],
    "Autumn": ["Herbst", "der"],
    "Winter": ["Winter", "der"],
}